[package]
name = "fuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
afl = "0.15"
mxd = { path = "..", default-features = false }

[features]
default = ["sqlite"]
sqlite = ["mxd/sqlite"]
postgres = ["mxd/postgres"]
